let videoData = [
  {
    id: 1,
    title: "Ruhsora Emm - Under The Influence (Chris Brown)",
    channel: "X-Faktor O'zbekiston",
    channelPhoto:
      "https://yt3.ggpht.com/Om0mmOcWC-yPkRyAaoF00KZrnbNEQbTg-zK7Ebk62UfqjHGiY_1UtaR9ul9qfb8EyGI27bYHHh4=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 210000,
    views: "1M",
    likes: 38000,
    dislikes: 2100,
    uploaded: "1 yil oldin",
    duration: "9:22",
    thumbnail: "thumbnails/ruxsora.avif",
    category: "Music",
    src: "https://www.youtube.com/embed/8RBm0qKOmHY",
    like: 102,
  },
  {
    id: 2,
    title: '"Yo‘q" deyishni bilish | Abdusattor Abduraximov',
    channel: "Maqsad Club",
    channelPhoto:
      "https://yt3.ggpht.com/BV5IwOdY0X_eLqssWRI3cc_w73WfzDAAhBxXjWHVruyVKKyYCg4mtBgB0bsmm30i_488Bkym8A=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 52500,
    views: "52K",
    likes: 4200,
    dislikes: 140,
    uploaded: "2 hafta oldin",
    duration: "5:15",
    thumbnail: "thumbnails/yoq-deyish.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/VaKz4Jbe6C0",
    like: 240,
  },
  {
    id: 3,
    title:
      "Sun’iy intellektni 5 karra yaxshiroq ishlating | Xurshid Maroziqov | Birfoiz",
    channel: "birfoizbilim",
    channelPhoto:
      "https://yt3.ggpht.com/R-bmxKk1oz327JRWlcmigEC6i7WflcFk7zzlODvYGLZ2iZZi2l-kyR2_Ac2ZPXB4TrE8GWrUYQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 134000,
    views: "71K",
    likes: 6300,
    dislikes: 300,
    uploaded: "1 oy oldin",
    duration: "21:17",
    thumbnail: "thumbnails/ai-5x.avif",
    category: "Texnologiya",
    src: "https://www.youtube.com/embed/Oxe8LZYK31w",
    like: 780,
  },
  {
    id: 4,
    title: "Tirik kitob - Xayrulla Asatov - Тирик китоб",
    channel: "Xayrulla Asatov",
    channelPhoto:
      "https://yt3.ggpht.com/0YTYDIIniz5lCR0vKyXoBvbAZ2lkIr9iW8nFp_TjiQKveU0wd-ClNhoMHxlvvG5OvdV6oUW5kpQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 89700,
    views: "381K",
    likes: 18000,
    dislikes: 900,
    uploaded: "5 kun oldin",
    duration: "4:53",
    thumbnail: "thumbnails/tirik-kitob.avif",
    category: "Madaniyat",
    src: "https://www.youtube.com/embed/bdEYgtmzQdk",
    like: 304,
  },
  {
    id: 5,
    title: "Siz bilmagan Minecraft",
    channel: "UPG",
    channelPhoto:
      "https://yt3.ggpht.com/2Qw5nLGk206cx1UzvsbJZh_kcW6gAtQnHT0bniVrl4bqG1RMrSJH-B-J0UX8Xltljv0RExpD=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 330000,
    views: "49K",
    likes: 3100,
    dislikes: 120,
    uploaded: "3 kun oldin",
    duration: "16:24",
    thumbnail: "thumbnails/minecraft.avif",
    category: "O‘yinlar",
    src: "https://www.youtube.com/embed/CgZ5ukSgubc",
    like: 932,
  },
  {
    id: 6,
    title: "Sizni Aqlliroq Qiluvchi 15 ta Odat!",
    channel: "Nurli Media",
    channelPhoto:
      "https://yt3.ggpht.com/ytc/AIdro_lTB6EGmAFhNDtpfRzK52Xsl4RtieuMLl1qj4uYcuv7Mw=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 412000,
    views: "338K",
    likes: 22000,
    dislikes: 1500,
    uploaded: "1 yil oldin",
    duration: "17:26",
    thumbnail: "thumbnails/aqlliroq.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/cA1Q5bFY5Z8",
    like: 65,
  },
  {
    id: 7,
    title:
      "DANGASALIKKA QARSHI 10 ta Oddiy Ammo Kuchli Texnika (100% Ishlaydi!)",
    channel: "DAVRONBEK TURDIEV",
    channelPhoto:
      "https://yt3.ggpht.com/NgMI5B2Sw4YiMFP4LQw5bNq4sTsBioMDXckxjxaOUTIfdkAS85R2Uzfhv5XAaEbY_Uk6pHUdfQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 278000,
    views: "170K",
    likes: 14000,
    dislikes: 600,
    uploaded: "3 hafta oldin",
    duration: "27:51",
    thumbnail: "thumbnails/dangasalikka-qarshi.avif",
    category: "Motivatsiya",
    src: "https://www.youtube.com/embed/uul53emqf10",
    like: 130,
  },
  {
    id: 8,
    title: "18 Years Old Cristiano Ronaldo was INSANE",
    channel: "VALENTINO PRODUCTIONS",
    channelPhoto:
      "https://yt3.ggpht.com/vyfJhgtTbO-NC8ymcLHCdtO7MhIIwReE2AxyP4jEljAdhh5MBOK1bQWeLheebwYW-3YttvNUrA=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 1200000,
    views: "10M",
    likes: 45000,
    dislikes: 19000,
    uploaded: "1 yil oldin",
    duration: "15:48",
    thumbnail: "thumbnails/ronaldo.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/XXYbVpkI-UY",
    like: 560,
  },
  {
    id: 9,
    title: "Nizamo.S & Umida Odilova - Yonimda qol | Низамо.С & Умида Одилова - Ёнимда кол",
    channel: "RIZA nova",
    channelPhoto:
      "https://yt3.ggpht.com/RgaUkLdAueTinVyeRN95_WNLohSq-mv2oViq-WefY4EjdGnQ5zlVHJgRswVreGbjgS3iIMRkyg=s88-c-k-c0x00ffffff-no-rj",
    subscribers: 12000000,
    views: "10M",
    likes: 10000,
    dislikes: 1000,
    uploaded: "1 kun oldin",
    duration: "2:46",
    thumbnail: "thumbnails/yonimda-qol.avif",
    category: "music",
    src: "https://www.youtube.com/embed/ZIsxXFG5W4I",
    like: 560,
  },
];

