let videoData = [
  {
    id: 1,
    title: "Ruhsora Emm - Under The Influence (Chris Brown)",
    channel: "X-Faktor O'zbekiston",
    channelPhoto:
      "https://yt3.ggpht.com/Om0mmOcWC-yPkRyAaoF00KZrnbNEQbTg-zK7Ebk62UfqjHGiY_1UtaR9ul9qfb8EyGI27bYHHh4=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 210000,
    views: "1M",
    likes: 38000,
    dislikes: 2100,
    uploaded: "1 yil oldin",
    duration: "9:22",
    thumbnail: "thumbnails/ruxsora.avif",
    category: "Music",
    src: "https://www.youtube.com/embed/8RBm0qKOmHY",
  },
  {
    id: 2,
    title: '"Yo‘q" deyishni bilish | Abdusattor Abduraximov',
    channel: "Maqsad Club",
    channelPhoto:
      "https://yt3.ggpht.com/BV5IwOdY0X_eLqssWRI3cc_w73WfzDAAhBxXjWHVruyVKKyYCg4mtBgB0bsmm30i_488Bkym8A=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 52500,
    views: "52K",
    likes: 4200,
    dislikes: 140,
    uploaded: "2 hafta oldin",
    duration: "5:15",
    thumbnail: "thumbnails/yoq-deyish.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/VaKz4Jbe6C0",
  },
  {
    id: 3,
    title:
      "Sun’iy intellektni 5 karra yaxshiroq ishlating | Xurshid Maroziqov | Birfoiz",
    channel: "birfoizbilim",
    channelPhoto:
      "https://yt3.ggpht.com/R-bmxKk1oz327JRWlcmigEC6i7WflcFk7zzlODvYGLZ2iZZi2l-kyR2_Ac2ZPXB4TrE8GWrUYQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 134000,
    views: "71K",
    likes: 6300,
    dislikes: 300,
    uploaded: "1 oy oldin",
    duration: "21:17",
    thumbnail: "thumbnails/ai-5x.avif",
    category: "Texnologiya",
    src: "https://www.youtube.com/embed/Oxe8LZYK31w",
  },
  {
    id: 4,
    title: "Tirik kitob - Xayrulla Asatov - Тирик китоб",
    channel: "Xayrulla Asatov",
    channelPhoto:
      "https://yt3.ggpht.com/0YTYDIIniz5lCR0vKyXoBvbAZ2lkIr9iW8nFp_TjiQKveU0wd-ClNhoMHxlvvG5OvdV6oUW5kpQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 89700,
    views: "381K",
    likes: 18000,
    dislikes: 900,
    uploaded: "5 kun oldin",
    duration: "4:53",
    thumbnail: "thumbnails/tirik-kitob.avif",
    category: "Madaniyat",
    src: "https://www.youtube.com/embed/bdEYgtmzQdk",
  },
  {
    id: 5,
    title: "Siz bilmagan Minecraft",
    channel: "UPG",
    channelPhoto:
      "https://yt3.ggpht.com/2Qw5nLGk206cx1UzvsbJZh_kcW6gAtQnHT0bniVrl4bqG1RMrSJH-B-J0UX8Xltljv0RExpD=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 330000,
    views: "49K",
    likes: 3100,
    dislikes: 120,
    uploaded: "3 kun oldin",
    duration: "16:24",
    thumbnail: "thumbnails/minecraft.avif",
    category: "O'yinlar",
    src: "https://www.youtube.com/embed/CgZ5ukSgubc",
  },
  {
    id: 6,
    title: "Sizni Aqlliroq Qiluvchi 15 ta Odat!",
    channel: "Nurli Media",
    channelPhoto:
      "https://yt3.ggpht.com/ytc/AIdro_lTB6EGmAFhNDtpfRzK52Xsl4RtieuMLl1qj4uYcuv7Mw=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 412000,
    views: "338K",
    likes: 22000,
    dislikes: 1500,
    uploaded: "1 yil oldin",
    duration: "17:26",
    thumbnail: "thumbnails/aqlliroq.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/cA1Q5bFY5Z8",
  },
  {
    id: 7,
    title:
      "DANGASALIKKA QARSHI 10 ta Oddiy Ammo Kuchli Texnika (100% Ishlaydi!)",
    channel: "DAVRONBEK TURDIEV",
    channelPhoto:
      "https://yt3.ggpht.com/NgMI5B2Sw4YiMFP4LQw5bNq4sTsBioMDXckxjxaOUTIfdkAS85R2Uzfhv5XAaEbY_Uk6pHUdfQ=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 278000,
    views: "170K",
    likes: 14000,
    dislikes: 600,
    uploaded: "3 hafta oldin",
    duration: "27:51",
    thumbnail: "thumbnails/dangasalikka-qarshi.avif",
    category: "Motivatsiya",
    src: "https://www.youtube.com/embed/uul53emqf10",
  },
  {
    id: 8,
    title: "18 Years Old Cristiano Ronaldo was INSANE",
    channel: "VALENTINO PRODUCTIONS",
    channelPhoto:
      "https://yt3.ggpht.com/vyfJhgtTbO-NC8ymcLHCdtO7MhIIwReE2AxyP4jEljAdhh5MBOK1bQWeLheebwYW-3YttvNUrA=s68-c-k-c0x00ffffff-no-rj",
    subscribers: 1200000,
    views: "10M",
    likes: 45000,
    dislikes: 19000,
    uploaded: "1 yil oldin",
    duration: "15:48",
    thumbnail: "thumbnails/ronaldo.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/XXYbVpkI-UY",
  },
  {
    id: 9,
    title: "Sheriff of Oddsville | Oddbods Cartoons | Funny Cartoons For Kids",
    channel: "Oddbods Cartoons",
    channelPhoto:
      "https://yt3.ggpht.com/6NeRLv3A-I9qna5Mk158cCVpqs54oIC0-2XqpKpAIVXxHyK_IcWlfwNhBP07KlCUCxHJfNTAy4Y=s68-c-k-c0x00ffffff-no-rj", // Agar siz aniq URL berishni istasangiz, bu yerga haqiqiy rasm manzili kiritiladi.
    views: "2.1M",
    uploaded: "4 months ago",
    duration: "1:37:47",
    thumbnail: "thumbnails/oddbods.avif",
    category: "Kids",
    src: "https://www.youtube.com/embed/Kdnri6JLJqY", // Video ID yo‘q, shuning uchun linkni to‘liq ko‘rsata olmayman.
  },

  {
    id: 10,
    title:
      "BUNAQA EL CLASICO TARIXDA BÒLMAGAN! BARCA vs REAL 3-QISM UNWANTED BOYS!",
    channel: " ABDUJABBOROV__7 -  UNWANTED BOYS",
    channelPhoto:
      "https://yt3.ggpht.com/1VddnzudOBTDvWLjO-_nOJ8pkNcA1wm6-46uBrj_7thtGWNQzBHxCC_b8AhIpI2wtlwUR8JZOg=s88-c-k-c0x00ffffff-no-rj",
    views: "405K",
    uploaded: " 8 days ago",
    duration: "23:425",
    thumbnail: "thumbnails/sm.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/xtZOYN61Y68",
  },
  {
    id: 11,
    title: "REAL MADRID - BARCELONA! El Clasico ABDUJABBOROV__7",
    channel: " ABDUJABBOROV__7 -  UNWANTED BOYS",
    channelPhoto:
      "https://yt3.ggpht.com/1VddnzudOBTDvWLjO-_nOJ8pkNcA1wm6-46uBrj_7thtGWNQzBHxCC_b8AhIpI2wtlwUR8JZOg=s88-c-k-c0x00ffffff-no-rj",
    views: "1.56M",
    uploaded: " 2 years ago ",
    duration: "7:44",
    thumbnail: "thumbnails/el.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/ZPPqsZgoYHo",
  },
  {
    id: 12,
    title:
      "Box Full of Model Cars -Mazda Mx5, Koenigesgg Jesko, Lamborghini Scv12, Byd Yang Wang U8, Toyota Car",
    channel: "  Desiliun Diecast",
    channelPhoto:
      "https://yt3.ggpht.com/EhzbF7BD4m5cezu9nb8CQuK6GB1nagQ3JfU7Vuked7DVa_fz4C4cuJNfuXCM0mTvYyhWBp7l9w=s88-c-k-c0x00ffffff-no-rj",
    views: "6",
    uploaded: " 86 minutes ago ",
    duration: "1:24:47",
    thumbnail: "thumbnails/mm.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/tvX1BgQh_sk",
  },
  {
    id: 13,
    title:
      "DLS 25 | How to Transfer Your Account On DLS25| Old Device to New Device",
    channel: "  GAMEFANS",
    channelPhoto:
      "https://yt3.ggpht.com/_mvO5sG4QTSek0TI1hBIygajwyiYyfQK_e381C7trqeeMxFsjDZT2u9Nd2xHaYXCcn0f5Sjq5g=s88-c-k-c0x00ffffff-no-rj",
    views: "6",
    uploaded: "4 months ago",
    duration: "10:49",
    thumbnail: "thumbnails/olo.avif",
    category: "O'yinlar",
    src: "https://www.youtube.com/embed/66AMwGmBdn8",
  },
  {
    id: 14,
    title: "O'gil bolada TESTASTEERON bo'ladi 😄😄😄 #qodirtolipov",
    channel: "  Kadir Tolipov",
    channelPhoto:
      "https://yt3.ggpht.com/ExnW-WpoEa9dVTo8n0fQRE2jjwjraFEdcGG9F1D6Mm3kiC1oYVOOZ0Jyes7Chj7RC73Vmu8zgQ=s88-c-k-c0x00ffffff-no-rj",
    views: "1M6",
    uploaded: "2 weeks  ago",
    duration: "10:20",
    thumbnail: "thumbnails/ky.avif",
    category: "Comedy",
    src: "https://www.youtube.com/embed/nENUBulDXKA",
  },
  {
    id: 15,
    title: "QODIR TOLIPOV / КОДИР ТОЛИПОВ / YANGI INSTAGRAM VAYNLAR",
    channel: " ARTIKSTUDIO ",
    channelPhoto:
      "https://yt3.ggpht.com/-joBKxHF7deRBmBVmR14x3OSA8IdrW0dMn6oDo2XRrehPW3Crd64vsNm8CE8Q0BgE5YffiBr=s88-c-k-c0x00ffffff-no-rj",
    views: "933K",
    uploaded: "5 months  ago",
    duration: "8:54",
    thumbnail: "thumbnails/oop.avif",
    category: "Comedy",
    src: "https://www.youtube.com/embed/7C4OCxvroU8",
  },
  {
    id: 16,
    title: "Qodir Tolipov yangi vine #trend #kulamiz",
    channel: "Kadir Tolipov",
    channelPhoto:
      "https://yt3.ggpht.com/ExnW-WpoEa9dVTo8n0fQRE2jjwjraFEdcGG9F1D6Mm3kiC1oYVOOZ0Jyes7Chj7RC73Vmu8zgQ=s88-c-k-c0x00ffffff-no-rj",
    views: "1.5K",
    uploaded: "2 days ago",
    duration: "3:45",
    thumbnail: "https://i.ytimg.com/vi/f1CaXzETGXo/hqdefault.jpg",
    category: "Comedy",
    src: "https://www.youtube.com/embed/f1CaXzETGXo",
  },
  {
    id: 17,
    title: "O'zbekistondagi Eng Qimmat Aktyorlar",
    channel: "Yulduzlar Hayati",
    channelPhoto:
      "https://yt3.ggpht.com/ytc/AIdro_l_y1DYnA1z55t7Y-azFOJsW9Y7IktMYJt_SRz_AWxU0Rw=s88-c-k-c0x00ffffff-no-rj",
    views: "698K ",
    uploaded: "3 years ago",
    duration: "2:52",
    thumbnail: "thumbnails/pp.avif",
    category: "Mashxurlar",
    src: "https://www.youtube.com/embed/pmRCR6PbXnk",
  },
];
